export const GET_WHEATHER_DATA_REQUEST = "GET_WHEATHER_DATA_REQUEST";
export const GET_WHEATHER_DATA_SUCCESS = "GET_WHEATHER_DATA_SUCCESS";
export const GET_WHEATHER_DATA_FAILURE = "GET_WHEATHER_DATA_FAILURE";


export const GET_FORCAST_DATA_REQUEST = "GET_FORCAST_DATA_REQUEST";
export const GET_FORCAST_DATA_SUCCESS = "GET_FORCAST_DATA_SUCCESS";
export const GET_FORCAST_DATA_FAILURE = "GET_FORCAST_DATA_FAILURE";